config/routes.rb
Carpool::Application.routes.draw do

  resources :addresses
  resources :models

  resources :users do
    resources :vehicles
  end

  controller :user_sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resource :account, :controller => "users", :as => :account

  resources :vehicles

  get "home/index"

  root :to => 'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/model.rb
class Model < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_destroy :set_obsolete
  acts_as_authentic 

  has_many :vehicles
  has_many :addresses

  def set_obsolete
    self.obsolete = true
    self.save
    false
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  belongs_to :user
  has_one :model

  scope :active,where(:retired_at => nil)

  def retire
    self.retired_at = Time.now
    self.save
  end
  
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def index
    @models = Model.all
    
    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @models }
    end
  end

  def edit
    @model = Model.find(params[:id])
  end

  def new
    @model = Model.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @model }
    end
  end

  def create
    @model = Model.new(params[:model])

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render json: @model, status: :created, location: @model }
      else
        format.html { render action: "new" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url }
      format.json { head :no_content }
    end
  end

  def show
    @model = Model.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end

  def update
    @model = Model.find(params[:id])
    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<section id="model_form" class="clearfix">
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand_name %><br />
    <%= f.text_field :brand_name %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.select :year, (1800..Time.now.year) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</section>

app/views/models/edit.html.erb
<h1>Edit Model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %>
<%= link_to 'Back', models_path %>

app/views/models/index.html.erb
<h1>Models#index</h1>
<table>
  <tr>
    <th>Brand Name</th>
    <th>Model</th>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @models.each do |model| %>
  <tr>
    <td><%= model.brand_name %></td>
    <td><%= model.model %></td>
    <td><%= model.year %></td>
    <td><%= link_to 'Show', model %></td>
    <td><%= link_to 'Edit', edit_model_path(model) %></td>
    <td><%= link_to 'Destroy', model, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br/>
<%= link_to 'New Model', new_model_path %>

app/views/models/new.html.erb
<h1>New Model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %>
<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<h1>Model</h1>

<section id="model-<%= @model.id %>">
<p>
  <b>Brand Name</b>
  <%= @model.brand_name %>
</p>
<p>
  <b>Model</b>
  <%= @model.model %>
</p>

<p>
  <b>Year</b>
  <%= @model.year %>
</p>

<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>

</section>