config/routes.rb
Carpool::Application.routes.draw do

  resources :addresses
  resources :models

  resources :users do
    resources :vehicles
  end

  controller :user_sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resource :account, :controller => "users", :as => :account

  resources :vehicles

  get "home/index"

  root :to => 'home#index'

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = current_user.addresses.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = current_user.addresses.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = current_user.addresses.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = current_user.addresses.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = current_user.addresses.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to user_addresses_path current_user, notice: 'The address has been deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<section id="address_form" class="clearfix">
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="map_canvas"></div>
  <div class="field">
    <%= f.label :address_1 %><br />
    <%= f.text_field :address_1 %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br />
    <%= f.text_field :address_2 %>
  </div>
  <div class="field">
    <%= f.label :suburb %><br />
    <%= f.text_field :suburb %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br />
    <%= f.number_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.number_field :longitude %>
  </div>
   <div class="field">
    <%= f.label :latitude %><br />
    <%= f.number_field :latitude %>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
  <div>
	<a id="show_on_map" href="#">show on map</a>
  </div>
<% end %>
</section>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Address 1</th>
    <th>Address 2</th>
    <th>Suburb</th>
    <th>Postcode</th>
    <th>State</th>
    <th>Country</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.address_1 %></td>
    <td><%= address.address_2 %></td>
    <td><%= address.suburb %></td>
    <td><%= address.postcode %></td>
    <td><%= address.state %></td>
    <td><%= address.country %></td>
    <td><%= address.latitude %></td>
    <td><%= address.longitude %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<section id="show_address" class="clearfix">

<input id="address_latitude" value="<%= @address.latitude %>" type="hidden"/>
<input id="address_longitude" value="<%= @address.longitude %>" type="hidden"/>
  <div id="map_canvas"></div>
  <p>
    <b>Address 1:</b>
    <%= @address.address_1 %>
  </p>

<% if @address.address_2.length > 0 %>
  <p>
    <b>Address 2:</b>
    <%= @address.address_2 %>
  </p>
<% end %>

  <p>
    <b>Suburb:</b>
    <%= @address.suburb %>
  </p>

  <p>
    <b>Postcode:</b>
    <%= @address.postcode %>
  </p>

  <p>
    <b>Country:</b>
    <%= @address.country %>
  </p>

  <%= link_to 'Edit', edit_address_path(@address) %> |
  <%= link_to 'Back', addresses_path %>
</section>